// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf-kofmz_9tFbtmuvP_M48SVbMcIZipgo',
    appId: '1:659958299934:web:001541fef04b525a331d0f',
    messagingSenderId: '659958299934',
    projectId: 'surgakicare',
    authDomain: 'surgakicare.firebaseapp.com',
    storageBucket: 'surgakicare.appspot.com',
    measurementId: 'G-0B27DVB72P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqgWNw8kYeMIKHvdeSbSSo_7C7sctMm8',
    appId: '1:659958299934:android:63cbf7654ee23076331d0f',
    messagingSenderId: '659958299934',
    projectId: 'surgakicare',
    storageBucket: 'surgakicare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN-HlLkGR_ItWTjNtUcCDWEfogh567p84',
    appId: '1:659958299934:ios:7fc2b6b1828346d5331d0f',
    messagingSenderId: '659958299934',
    projectId: 'surgakicare',
    storageBucket: 'surgakicare.appspot.com',
    iosBundleId: 'com.example.surgakicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN-HlLkGR_ItWTjNtUcCDWEfogh567p84',
    appId: '1:659958299934:ios:7fc2b6b1828346d5331d0f',
    messagingSenderId: '659958299934',
    projectId: 'surgakicare',
    storageBucket: 'surgakicare.appspot.com',
    iosBundleId: 'com.example.surgakicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf-kofmz_9tFbtmuvP_M48SVbMcIZipgo',
    appId: '1:659958299934:web:dc3ee00a0eaf7f2e331d0f',
    messagingSenderId: '659958299934',
    projectId: 'surgakicare',
    authDomain: 'surgakicare.firebaseapp.com',
    storageBucket: 'surgakicare.appspot.com',
    measurementId: 'G-CWK10E45PH',
  );
}
